// nuxt-app/src/modules/home/components/Post.vue
<template>
  <article class="post">
    <section>
      <nuxt-link :to="`/post/${post.id}`">
        <h2>{{ post.title }}</h2>
      </nuxt-link>
      <h4>{{ post.body }}</h4>
    </section>
  </article>
</template>

<script>
export default {
  props: {
    post: Object
  }
};
</script>

<style lang="scss" scoped>
.post {
  padding: 1rem;
}
</style>

// sapper-app/src/modules/home/components/Post.svelte
<script>
    export let post;
</script>

<article class="post">
    <section>
        <a rel="prefetch" href={`/post/${post.id}`}>
            <h2>{post.title}</h2>
        </a>
        <h4>{post.body}</h4>
    </section>
</article>

<style lang="scss">
    .post {
        padding: 1rem;
    }
</style>
