// nuxt-app/src/modules/post/components/CommentList.vue
<template>
  <ul class="comments">
    <li v-for="c in comments" :key="c.id">
      <Comment :comment="c" />
    </li>
  </ul>
</template>

<script>
import Comment from './Comment';

export default {
  components: { Comment },
  props: {
    comments: { type: Array, required: true }
  }
};
</script>

<style lang="scss" scoped>
@import '../../../common/style/mixins.scss';

.comments {
  @include ul-reset;
}
</style>

// sapper-app/src/modules/post/components/CommentList.svelte
<script>
    import Comment from './Comment.svelte';

    export let comments;
</script>

<ul class="comments">
    {#each comments as c (c.id)}
        <li>
            <Comment comment={c} />
        </li>
    {/each}
</ul>

<style lang="scss">
    @import '../../../common/style/mixins.scss';

    .comments {
        @include ul-reset;
    }
</style>
