// nuxt-app/src/modules/post/containers/CommentContainer.vue
<template>
  <section>
    <p v-if="pending" class="message">Loading...</p>
    <CommentList v-else-if="comments" :comments="comments" />
    <p v-else class="message">An error occured.</p>
  </section>
</template>

<script>
import { httpService } from '../../../config/rootService';
import { postsUrl } from '../../../config/variables';
import CommentList from '../components/CommentList';

export default {
  components: { CommentList },
  props: {
    postId: { type: Number, required: true }
  },
  data() {
    return {
      pending: true,
      error: null,
      comments: null
    };
  },
  mounted() {
    httpService
      .get(`${postsUrl}/${this.postId}/comments`)
      .then((comments) => {
        this.pending = false;
        this.error = null;
        this.comments = comments;
      })
      .catch((err) => {
        this.pending = false;
        this.error = err;
      });
  }
};
</script>
<style lang="scss" scoped>
.message {
  text-align: center;
  font-size: 2rem;
}
</style>

// sapper-app/src/modules/post/containers/CommentContainer.svelte
<script>
    import { postsUrl } from '../../../config/variables';
    import { httpService } from '../../../config/rootService';
    import CommentList from '../components/CommentList.svelte';

    export let postId;

    $: commentsPromise = httpService.get(`${postsUrl}/${postId}/comments`);
</script>

<section>
    {#await commentsPromise}
        <p class="message">Loading...</p>
    {:then comments}
        <CommentList {comments} />
    {:catch}
        <p class="message">An error occured.</p>
    {/await}
</section>

<style lang="scss">
    .message {
        text-align: center;
        font-size: 2rem;
    }
</style>
