// sapper-app/src/modules/home/components/PostList.svelte
<script>
    import Post from './Post.svelte';

    export let posts;
</script>

<ul class="post__list">
    {#each posts as p (p.id)}
        <li>
            <Post post={p} />
        </li>
    {/each}
</ul>

<style lang="scss">
    @import '../../../common/style/mixins.scss';

    .post__list {
        @include ul-reset;
        padding: 0 3rem;
    }
</style>

// nuxt-app/src/modules/home/components/PostList.vue
<template>
  <section>
    <ul v-for="p in posts" :key="p.id" class="post__list">
      <li>
        <Post :post="p" />
      </li>
    </ul>
  </section>
</template>

<script>
import Post from './Post.vue';

export default {
  components: { Post },
  props: {
    posts: Array
  }
};
</script>

<style lang="scss" scoped>
@import '../../../common/style/mixins.scss';

.post__list {
  @include ul-reset;
  padding: 0 3rem;
}
</style>
